### ISSUE TITLE
Junos_interface is giving syntax based error

### ISSUE THREAD

**Issue by rahkumar651991** [ansible-collections/junipernetworks.junos#120]
##### SUMMARY

Junos_interface is not working and giving syntax based error

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

junos_interface

##### ANSIBLE VERSION

```paste below
  ansible-playbook 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.8.5 (default, Aug 12 2020, 00:00:00) [GCC 10.2.1 20200723 (Red Hat 10.2.1-1)]
```

##### CONFIGURATION

```paste below
DEFAULT_FORKS(/Users/rahkumar/Ansible_Module_Examples/ansible.cfg) = 10
DEFAULT_GATHERING(/Users/rahkumar/Ansible_Module_Examples/ansible.cfg) = explicit
DEFAULT_HASH_BEHAVIOUR(/Users/rahkumar/Ansible_Module_Examples/ansible.cfg) = merge
DEFAULT_HOST_LIST(/Users/rahkumar/Ansible_Module_Examples/ansible.cfg) = ['/Users/rahkumar/Ansible_Module_Examples/inventory']
DEFAULT_LOG_PATH(/Users/rahkumar/Ansible_Module_Examples/ansible.cfg) = /Users/rahkumar/.ansible/log/ansible.log
DEFAULT_ROLES_PATH(/Users/rahkumar/Ansible_Module_Examples/ansible.cfg) = ['/Users/rahkumar/.ansible/roles']
HOST_KEY_CHECKING(/Users/rahkumar/Ansible_Module_Examples/ansible.cfg) = False
RETRY_FILES_SAVE_PATH(/Users/rahkumar/Ansible_Module_Examples/ansible.cfg) = /Users/rahkumar/.ansible/retry

```

##### OS / ENVIRONMENT

Linux

##### STEPS TO REPRODUCE

```yaml
    - name: Retrieve facts from devices running Junos OS
      junos_interface:
        name: xe-0/2/1
        enabled: false
```

##### EXPECTED RESULTS

It is expected to pass. We tried running individual rpc as seen in netconf trace and it executes fine on the device. 

##### ACTUAL RESULTS

```paste below
TASK [Disabling switch port] *******************************************************************************************************************************************************************************
task path: /home/lab/juniper_port_down.yml:8
<lab10e-sw02> ESTABLISH LOCAL CONNECTION FOR USER: lab
<lab10e-sw02> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/lab/.ansible/tmp/ansible-local-31220jdy7mg4w `"&& mkdir "` echo /home/lab/.ansible/tmp/ansible-local-31220jdy7mg4w/ansible-tmp-1602684919.813968-31226-42833055793085 `" && echo ansible-tmp-1602684919.813968-31226-42833055793085="` echo /home/lab/.ansible/tmp/ansible-local-31220jdy7mg4w/ansible-tmp-1602684919.813968-31226-42833055793085 `" ) && sleep 0'
Using module file /home/lab/.ansible/collections/ansible_collections/junipernetworks/junos/plugins/modules/junos_interfaces.py
<lab10e-sw02> PUT /home/lab/.ansible/tmp/ansible-local-31220jdy7mg4w/tmpmlxu_q7q TO /home/lab/.ansible/tmp/ansible-local-31220jdy7mg4w/ansible-tmp-1602684919.813968-31226-42833055793085/AnsiballZ_junos_interfaces.py
<lab10e-sw02> EXEC /bin/sh -c 'chmod u+x /home/lab/.ansible/tmp/ansible-local-31220jdy7mg4w/ansible-tmp-1602684919.813968-31226-42833055793085/ /home/lab/.ansible/tmp/ansible-local-31220jdy7mg4w/ansible-tmp-1602684919.813968-31226-42833055793085/AnsiballZ_junos_interfaces.py && sleep 0'
<lab10e-sw02> EXEC /bin/sh -c '/usr/bin/python3 /home/lab/.ansible/tmp/ansible-local-31220jdy7mg4w/ansible-tmp-1602684919.813968-31226-42833055793085/AnsiballZ_junos_interfaces.py && sleep 0'
<lab10e-sw02> EXEC /bin/sh -c 'rm -f -r /home/lab/.ansible/tmp/ansible-local-31220jdy7mg4w/ansible-tmp-1602684919.813968-31226-42833055793085/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
File "/tmp/ansible_junipernetworks.junos.junos_interfaces_payload_4q1uw620/ansible_junipernetworks.junos.junos_interfaces_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/netconf.py", line 91, in parse_rpc_error
File "src/lxml/etree.pyx", line 3237, in lxml.etree.fromstring
File "src/lxml/parser.pxi", line 1896, in lxml.etree._parseMemoryDocument
File "src/lxml/parser.pxi", line 1784, in lxml.etree._parseDoc
File "src/lxml/parser.pxi", line 1141, in lxml.etree._BaseParser._parseDoc
File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
File "<string>", line 1
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/lab/.ansible/tmp/ansible-local-31220jdy7mg4w/ansible-tmp-1602684919.813968-31226-42833055793085/AnsiballZ_junos_interfaces.py", line 102, in <module>
_ansiballz_main()
File "/home/lab/.ansible/tmp/ansible-local-31220jdy7mg4w/ansible-tmp-1602684919.813968-31226-42833055793085/AnsiballZ_junos_interfaces.py", line 94, in _ansiballz_main
invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
File "/home/lab/.ansible/tmp/ansible-local-31220jdy7mg4w/ansible-tmp-1602684919.813968-31226-42833055793085/AnsiballZ_junos_interfaces.py", line 40, in invoke_module
runpy.run_module(mod_name='ansible_collections.junipernetworks.junos.plugins.modules.junos_interfaces', init_globals=None, run_name='__main__', alter_sys=True)
File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
return _run_module_code(code, init_globals, run_name, mod_spec)
File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
mod_name, mod_spec, pkg_name, script_name)
File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
```

**Comment by ashwini-mhatre** [comment]
@rahkumar651991 which module you are using because the task shared and the logs are contradicting each other? Are you using junipernetworks.junos collection along with ansible?

**Comment by rahkumar651991** [comment]
@ashwini-mhatre  - You may mention complete junipernetworks.junos.junos_interface in tasks or mention collection at the top of playbook and modules in the tasks. 

If it is deprecated then it is a different thing but it doesn't seem to be working earlier.

**Comment by ashwini-mhatre** [comment]
@rahkumar651991 can you please also share detailed debug logs https://docs.ansible.com/ansible/devel/network/user_guide/network_debug_troubleshooting.html#enabling-networking-device-interaction-logging.
