### ISSUE TITLE
junipernetworks.junos.junos_facts throws an error

### ISSUE THREAD

**Issue by XenGi** [ansible-collections/junipernetworks.junos#122]
##### SUMMARY
I'm trying to get all facts from a juniper switch but the facts module fails to do so.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
junipernetworks.junos.junos_facts module

##### ANSIBLE VERSION

```
ansible 2.10.3
  config file = /foobar/ansible.cfg
  configured module search path = ['/foo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /foo/.pyvenvs/ansible_networking/lib/python3.8/site-packages/ansible
  executable location = /foo/.pyvenvs/ansible_networking/bin/ansible
  python version = 3.8.6 (default, Sep 30 2020, 04:00:38) [GCC 10.2.0]
```

##### CONFIGURATION

```
ANSIBLE_NOCOWS(/foobar/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/foobar/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s
ANSIBLE_SSH_CONTROL_PATH(/foobar/ansible.cfg) = %(directory)s/%%C
ANSIBLE_SSH_CONTROL_PATH_DIR(/foobar/ansible.cfg) = /tmp
COLLECTIONS_PATHS(/foobar/ansible.cfg) = ['/foobar/collections']
DEFAULT_HOST_LIST(/foobar/ansible.cfg) = ['/foobar/inventory']
DEFAULT_REMOTE_PORT(/foobar/ansible.cfg) = 22
DEFAULT_REMOTE_USER(/foobar/ansible.cfg) = ricardo.band
DEFAULT_ROLES_PATH(/foobar/ansible.cfg) = ['/foobar/roles']
DEFAULT_STDOUT_CALLBACK(/foobar/ansible.cfg) = yaml
HOST_KEY_CHECKING(/foobar/ansible.cfg) = False
INTERPRETER_PYTHON(/foobar/ansible.cfg) = /usr/bin/python3
PERSISTENT_COMMAND_TIMEOUT(/foobar/ansible.cfg) = 30
PERSISTENT_CONNECT_RETRY_TIMEOUT(/foobar/ansible.cfg) = 15
PERSISTENT_CONNECT_TIMEOUT(/foobar/ansible.cfg) = 30
```

##### OS / ENVIRONMENT

```
$ uname -a
Linux lucy 5.9.1-arch1-1 #1 SMP PREEMPT Sat, 17 Oct 2020 13:30:37 +0000 x86_64 GNU/Linux
$ python --version
Python 3.8.6
```
Switch is a `QFX5100-24Q-3AFO` with firmware `14.1X53-D45.3`.

##### STEPS TO REPRODUCE

```yaml
---
- hosts: core
  tasks:
    - name: collect default set of facts
      junipernetworks.junos.junos_facts:
        gather_network_resources: all
        gather_subset: all
      register: _devices

    - debug:
        var: _devices
```

##### EXPECTED RESULTS

It should give me a pretty big dictionary with all the gathered facts.

##### ACTUAL RESULTS

```
ansible-playbook play.yml -v
Using /foobar/ansible.cfg as config file

PLAY [core] *************************************************************

TASK [Gathering Facts] **************************************************
[WARNING]: Ignoring timeout(10) for junipernetworks.junos.junos_facts
ok: [core-01.example.io]

TASK [collect default set of facts] *************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NameError: name 'new_ele' is not defined
fatal: [core-01.example.io]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "/foo/.ansible/tmp/ansible-local-775527vaydzqy3/ansible-tmp-1604671561.1315966-775613-110586876082641/AnsiballZ_junos_facts.py", line 102, in <module>
        _ansiballz_main()
      File "/foo/.ansible/tmp/ansible-local-775527vaydzqy3/ansible-tmp-1604671561.1315966-775613-110586876082641/AnsiballZ_junos_facts.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/foo/.ansible/tmp/ansible-local-775527vaydzqy3/ansible-tmp-1604671561.1315966-775613-110586876082641/AnsiballZ_junos_facts.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.junipernetworks.junos.plugins.modules.junos_facts', init_globals=None, run_name='__main__', alter_sys=True)
      File "/usr/lib/python3.8/runpy.py", line 207, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_junipernetworks.junos.junos_facts_payload_edikinj4/ansible_junipernetworks.junos.junos_facts_payload.zip/ansible_collections/junipernetworks/junos/plugins/modules/junos_facts.py", line 147, in <module>
      File "/tmp/ansible_junipernetworks.junos.junos_facts_payload_edikinj4/ansible_junipernetworks.junos.junos_facts_payload.zip/ansible_collections/junipernetworks/junos/plugins/modules/junos_facts.py", line 138, in main
      File "/tmp/ansible_junipernetworks.junos.junos_facts_payload_edikinj4/ansible_junipernetworks.junos.junos_facts_payload.zip/ansible_collections/junipernetworks/junos/plugins/module_utils/network/junos/facts/facts.py", line 114, in get_facts
      File "/tmp/ansible_junipernetworks.junos.junos_facts_payload_edikinj4/ansible_junipernetworks.junos.junos_facts_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 131, in get_network_resources_facts
      File "/tmp/ansible_junipernetworks.junos.junos_facts_payload_edikinj4/ansible_junipernetworks.junos.junos_facts_payload.zip/ansible_collections/junipernetworks/junos/plugins/module_utils/network/junos/facts/interfaces/interfaces.py", line 74, in populate_facts
      File "/tmp/ansible_junipernetworks.junos.junos_facts_payload_edikinj4/ansible_junipernetworks.junos.junos_facts_payload.zip/ansible_collections/junipernetworks/junos/plugins/module_utils/network/junos/utils/utils.py", line 29, in get_resource_config
    NameError: name 'new_ele' is not defined
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

PLAY RECAP **************************************************************
core-01.example.io : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

The name error on "new_ele" sounds like that ether the variable doesn't container the needed XML object to have that function or the "new_element" string got cut off somewhere if this is the full name. Haven't looked at the code level yet.

**Comment by rohitthakur2590** [comment]
@XenGi new_ele is imported from ncclient.xml_, you might need to update the ncclient version.
Let me know if that works for you.

**Comment by XenGi** [comment]
I think I already got the newest version.
```
$ pip freeze | grep ncclient
ncclient==0.6.9
```

**Comment by rohitthakur2590** [comment]
@XenGi  Do you still facing this issue?  If so one reason could be not having lxml installed for the dev env.
or could you please provide detailed logs?

**Comment by rohitthakur2590** [comment]
This seems to be a dependency problem at setup locally. If still persist please feel free to open a new issue/querry.
