### ISSUE TITLE
Cannot Gather Facts with `junos_facts`

### ISSUE THREAD

**Issue by harrytruman** [ansible-collections/junipernetworks.junos#17]
##### SUMMARY
When running the `junos_facts` module against our inventory, we encounter this error:
AttributeError: 'NoneType' object has no attribute 'text'

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
junos_facts

##### ANSIBLE VERSION
```paste below
ansible 2.9.6
 config file = /etc/ansible/ansible.cfg
 configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
 ansible python module location = /var/lib/awx/venv/mypy3/lib64/python3.6/site-packages/ansible
 executable location = /var/lib/awx/venv/mypy3/bin/ansible
 python version = 3.6.9 (default, Sep 11 2019, 16:40:19) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

```paste below
DEFAULT_VAULT_PASSWORD_FILE(/etc/ansible/ansible.cfg) = /etc/ansible/vault_password_file
```

##### OS / ENVIRONMENT
Junos 15.1f5 devices

##### STEPS TO REPRODUCE
Running fact collection through the resource modules will cause this problem:

```yaml
- name: junos_facts
  junos_facts:
gather_network_resources: ['all']
```

##### EXPECTED RESULTS
We should get a return of Ansible Facts for the Junos devices.

##### ACTUAL RESULTS
```paste below
TASK [roles/action/get_facts/junos : junos_facts] ******************************
task path: /tmp/awx_2382_ojfvvlq5/project/roles/action/get_facts/junos/tasks/main.yml:2
The full traceback is:
Traceback (most recent call last):
  File "/var/lib/awx/.ansible/tmp/ansible-tmp-1588009194.7062397-175641812749303/AnsiballZ_junos_facts.py", line 102, in <module>
    _ansiballz_main()
  File "/var/lib/awx/.ansible/tmp/ansible-tmp-1588009194.7062397-175641812749303/AnsiballZ_junos_facts.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/var/lib/awx/.ansible/tmp/ansible-tmp-1588009194.7062397-175641812749303/AnsiballZ_junos_facts.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.network.junos.junos_facts', init_globals=None, run_name='__main__', alter_sys=True)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_junos_facts_payload_ihoepdgj/ansible_junos_facts_payload.zip/ansible/modules/network/junos/junos_facts.py", line 135, in <module>
  File "/tmp/ansible_junos_facts_payload_ihoepdgj/ansible_junos_facts_payload.zip/ansible/modules/network/junos/junos_facts.py", line 126, in main
  File "/tmp/ansible_junos_facts_payload_ihoepdgj/ansible_junos_facts_payload.zip/ansible/module_utils/network/junos/facts/facts.py", line 62, in get_facts
  File "/tmp/ansible_junos_facts_payload_ihoepdgj/ansible_junos_facts_payload.zip/ansible/module_utils/network/common/facts/facts.py", line 105, in get_network_resources_facts
  File "/tmp/ansible_junos_facts_payload_ihoepdgj/ansible_junos_facts_payload.zip/ansible/module_utils/network/junos/facts/l3_interfaces/l3_interfaces.py", line 72, in populate_facts
  File "/tmp/ansible_junos_facts_payload_ihoepdgj/ansible_junos_facts_payload.zip/ansible/module_utils/network/junos/facts/l3_interfaces/l3_interfaces.py", line 93, in parse_l3_if_resources
AttributeError: 'NoneType' object has no attribute 'text'
fatal: [hostname]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\\n  File \\"/var/lib/awx/.ansible/tmp/ansible-tmp-1588009194.7062397-175641812749303/AnsiballZ_junos_facts.py\\", line 102, in <module>\\n    _ansiballz_main()\\n  File \\"/var/lib/awx/.ansible/tmp/ansible-tmp-1588009194.7062397-175641812749303/AnsiballZ_junos_facts.py\\", line 94, in _ansiballz_main\\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\\n  File \\"/var/lib/awx/.ansible/tmp/ansible-tmp-1588009194.7062397-175641812749303/AnsiballZ_junos_facts.py\\", line 40, in invoke_module\\n    runpy.run_module(mod_name='ansible.modules.network.junos.junos_facts', init_globals=None, run_name='__main__', alter_sys=True)\\n  File \\"/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py\\", line 205, in run_module\\n    return _run_module_code(code, init_globals, run_name, mod_spec)\\n  File \\"/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py\\", line 96, in _run_module_code\\n    mod_name, mod_spec, pkg_name, script_name)\\n  File \\"/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py\\", line 85, in _run_code\\n    exec(code, run_globals)\\n  File \\"/tmp/ansible_junos_facts_payload_ihoepdgj/ansible_junos_facts_payload.zip/ansible/modules/network/junos/junos_facts.py\\", line 135, in <module>\\n  File \\"/tmp/ansible_junos_facts_payload_ihoepdgj/ansible_junos_facts_payload.zip/ansible/modules/network/junos/junos_facts.py\\", line 126, in main\\n  File \\"/tmp/ansible_junos_facts_payload_ihoepdgj/ansible_junos_facts_payload.zip/ansible/module_utils/network/junos/facts/facts.py\\", line 62, in get_facts\\n  File \\"/tmp/ansible_junos_facts_payload_ihoepdgj/ansible_junos_facts_payload.zip/ansible/module_utils/network/common/facts/facts.py\\", line 105, in get_network_resources_facts\\n  File \\"/tmp/ansible_junos_facts_payload_ihoepdgj/ansible_junos_facts_payload.zip/ansible/module_utils/network/junos/facts/l3_interfaces/l3_interfaces.py\\", line 72, in populate_facts\\n  File \\"/tmp/ansible_junos_facts_payload_ihoepdgj/ansible_junos_facts_payload.zip/ansible/module_utils/network/junos/facts/l3_interfaces/l3_interfaces.py\\", line 93, in parse_l3_if_resources\\nAttributeError: 'NoneType' object has no attribute 'text'\\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by danielmellado** [comment]
Hi @harrytruman I'd need to get some more info about this, although I might have an idea about the issue. So far couldn't reproduce it myself. Mind telling me about the ansible version you're using and posting your ```show configuration interfaces```?

**Comment by danielmellado** [comment]
In any case, besides a minor issue, which I sorted out at [1], I was able to go ahead and gather all the facts without issue.

[1] https://github.com/ansible-collections/junipernetworks.junos/pull/20

**Comment by benjdudas** [comment]
Hey @danielmellado, this seems to be an issue when interfaces are added without unit configuration.

For example, the task will fail in this way with the following interface configuration.  
```
bdudas> show configuration interfaces
gr-0/0/0 {
    description "test with no unit";
}
ge-0/0/15 {
    unit 0 {
        family inet {
            address 192.168.0.1/32;
        }
    }
}
```
If I add unit config or just remove that interface it will be successfull.

Working config:
```
bdudas> show configuration interfaces
gr-0/0/0 {
    description "test with unit";
    unit 0;
}
ge-0/0/15 {
    unit 0 {
        family inet {
            address 192.168.0.1/32;
        }
    }
}
```

**Comment by benjdudas** [comment]
Adding `if iface.find("unit") is not None:` seems to work

```python
def parse_l3_if_resources(self, l3_if_resources):
        l3_ifaces = []
        for iface in l3_if_resources:
            interface = {}
            interface["name"] = iface.find("name").text
            if iface.find("description") is not None:
                interface["description"] = iface.find("description").text
            if iface.find("unit") is not None:
                interface["unit"] = iface.find("unit/name").text
            family = iface.find("unit/family/")
            if family is not None and family.tag != "ethernet-switching":
                ipv4 = iface.findall("unit/family/inet/address")
                dhcp = iface.findall("unit/family/inet/dhcp")
                ipv6 = iface.findall("unit/family/inet6/address")
                if dhcp:
                    interface["ipv4"] = [{"address": "dhcp"}]
                if ipv4:
                    interface["ipv4"] = self.get_ip_addresses(ipv4)
                elif not dhcp:
                    interface["ipv4"] = None
                if ipv6:
                    interface["ipv6"] = self.get_ip_addresses(ipv6)
                l3_ifaces.append(interface)
        return l3_ifaces
```

https://github.com/benjdudas/junipernetworks.junos/blob/3fa1efb7b05209104cf5d67436cb70442aeed7cb/plugins/module_utils/network/junos/facts/l3_interfaces/l3_interfaces.py#L103

**Comment by harrytruman** [comment]
@danielmellado @benjdudas That did it! Thank you both!
