### ISSUE TITLE
junos_user sshkey does not search through files directory

### ISSUE THREAD

**Issue by lazzarello** [ansible-collections/junipernetworks.junos#241]
##### SUMMARY
A task to create a user with the junos_user module fails in check mode when the `sshkey: "filename.pub"` parameter is set. `filename.pub` is located in a role at `roles/switch-user/files/filename.pub`. If I reference this file using a function, the task succeeds but this requires an absolute path to my local filesystem.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
junipernetworks.junos.junos_user

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.10.1
  config file = /home/lee/src/stand/ansible/ansible.cfg
  configured module search path = ['/home/lee/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/lee/.pyenv/versions/3.7.7/lib/python3.7/site-packages/ansible
  executable location = /home/lee/.pyenv/versions/3.7.7/bin/ansible
  python version = 3.7.7 (default, Aug  1 2020, 23:00:14) [GCC 9.3.0]
```

##### COLLECTION VERSION

```paste below
$ ansible-galaxy collection list junipernetworks.junos

# /home/lee/.ansible/collections/ansible_collections
Collection            Version
--------------------- -------
junipernetworks.junos 2.2.0 
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
ANSIBLE_SSH_ARGS(/home/lee/src/stand/ansible/ansible.cfg) = -o StrictHostKeyChecking=no -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s
DEFAULT_HOST_LIST(/home/lee/src/stand/ansible/ansible.cfg) = ['/home/lee/src/stand/ansible/hosts']
DEFAULT_STDOUT_CALLBACK(/home/lee/src/stand/ansible/ansible.cfg) = yaml
HOST_KEY_CHECKING(/home/lee/src/stand/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
```
    net_python_version: 3.7.7
    net_routing_engines:
      '0':
        cpu_background: '0'
        cpu_idle: '56'
        cpu_interrupt: '2'
        cpu_system: '20'
        cpu_temperature: 42 degrees C / 107 degrees F
        cpu_user: '22'
        last_reboot_reason: 0x1:power cycle/failure
        load_average_fifteen: '0.26'
        load_average_five: '0.29'
        load_average_one: '0.37'
        mastership_state: master
        memory_buffer_utilization: '14'
        memory_dram_size: 1945 MB
        memory_installed_size: (2048 MB installed)
        model: RE-EX3400-48P
        serial_number: BUILTIN
        slot: '0'
        start_time: 2021-03-30 06:23:25 PDT
        status: OK
        temperature: 42 degrees C / 107 degrees F
        up_time: 7 days, 1 hour, 9 minutes, 17 seconds
      '1':
        cpu_background: '0'
        cpu_idle: '77'
        cpu_interrupt: '1'
        cpu_system: '10'
        cpu_temperature: 29 degrees C / 84 degrees F
        cpu_user: '13'
        last_reboot_reason: 0x1:power cycle/failure
        load_average_fifteen: '0.26'
        load_average_five: '0.31'
        load_average_one: '0.38'
        mastership_state: backup
        memory_buffer_utilization: '12'
        memory_dram_size: 1945 MB
        model: RE-EX3400-48P
        serial_number: BUILTIN
        slot: '1'
        start_time: 2000-08-02 13:43:53 PDT
        status: OK
        temperature: 29 degrees C / 84 degrees F
        up_time: 7 days, 1 hour, 8 minutes, 41 seconds
    net_serialnum: NY0217100348
    net_system: junos
    net_version: 18.2R3-S5.3
```

##### STEPS TO REPRODUCE
The following task fails in check mode when run from a role with `"junos-superuser.key.pub"` located in that role's `files/` directory.

```yaml
- name: "add user"
  junipernetworks.junos.junos_user:
    name: user
    role: super-user
    # there is a bug in this module when including a file in the role by name. reported upstream.
    sshkey: "junos-superuser.key.pub"
    # sshkey: "{{ lookup('file', '~/.ssh/junos-superuser.key.pub') }}"
    state: present
```
##### EXPECTED RESULTS

The public key is added to the new user created by the task.

##### ACTUAL RESULTS
exception thrown, output implies the file is not being read and the value of `ssh_rsa` is not being set.

```paste below
redirecting (type: connection) ansible.builtin.netconf to ansible.netcommon.netconf
redirecting (type: netconf) ansible.builtin.junos to junipernetworks.junos.junos
redirecting (type: action) junipernetworks.junos.junos_user to junipernetworks.junos.junos
redirecting (type: action) junipernetworks.junos.junos_user to junipernetworks.junos.junos
<10.32.2.5> ESTABLISH LOCAL CONNECTION FOR USER: lee
<10.32.2.5> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/lee/.ansible/tmp/ansible-local-7443558se_mcu4 `"&& mkdir "` echo /home/lee/.ansible/tmp/ansible-local-7443558se_mcu4/ansible-tmp-1632873904.8801036-744508-196503813184442 `" && echo ansible-tmp-1632873904.8801036-744508-196503813184442="` echo /home/lee/.ansible/tmp/ansible-local-7443558se_mcu4/ansible-tmp-1632873904.8801036-744508-196503813184442 `" ) && sleep 0'
Using module file /home/lee/.ansible/collections/ansible_collections/junipernetworks/junos/plugins/modules/junos_user.py
<10.32.2.5> PUT /home/lee/.ansible/tmp/ansible-local-7443558se_mcu4/tmp45zfe0o1 TO /home/lee/.ansible/tmp/ansible-local-7443558se_mcu4/ansible-tmp-1632873904.8801036-744508-196503813184442/AnsiballZ_junos_user.py
<10.32.2.5> EXEC /bin/sh -c 'chmod u+x /home/lee/.ansible/tmp/ansible-local-7443558se_mcu4/ansible-tmp-1632873904.8801036-744508-196503813184442/ /home/lee/.ansible/tmp/ansible-local-7443558se_mcu4/ansible-tmp-1632873904.8801036-744508-196503813184442/AnsiballZ_junos_user.py && sleep 0'
<10.32.2.5> EXEC /bin/sh -c '/usr/bin/env python3 /home/lee/.ansible/tmp/ansible-local-7443558se_mcu4/ansible-tmp-1632873904.8801036-744508-196503813184442/AnsiballZ_junos_user.py && sleep 0'
<10.32.2.5> EXEC /bin/sh -c 'rm -f -r /home/lee/.ansible/tmp/ansible-local-7443558se_mcu4/ansible-tmp-1632873904.8801036-744508-196503813184442/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/lee/.ansible/tmp/ansible-local-7443558se_mcu4/ansible-tmp-1632873904.8801036-744508-196503813184442/AnsiballZ_junos_user.py", line 102, in <module>
    _ansiballz_main()
  File "/home/lee/.ansible/tmp/ansible-local-7443558se_mcu4/ansible-tmp-1632873904.8801036-744508-196503813184442/AnsiballZ_junos_user.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/lee/.ansible/tmp/ansible-local-7443558se_mcu4/ansible-tmp-1632873904.8801036-744508-196503813184442/AnsiballZ_junos_user.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.junipernetworks.junos.plugins.modules.junos_user', init_globals=None, run_name='__main__', alter_sys=True)
  File "/home/lee/.pyenv/versions/3.7.7/lib/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/home/lee/.pyenv/versions/3.7.7/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/lee/.pyenv/versions/3.7.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_junipernetworks.junos.junos_user_payload_mzzlhlry/ansible_junipernetworks.junos.junos_user_payload.zip/ansible_collections/junipernetworks/junos/plugins/modules/junos_user.py", line 461, in <module>
  File "/tmp/ansible_junipernetworks.junos.junos_user_payload_mzzlhlry/ansible_junipernetworks.junos.junos_user_payload.zip/ansible_collections/junipernetworks/junos/plugins/modules/junos_user.py", line 433, in main
  File "/tmp/ansible_junipernetworks.junos.junos_user_payload_mzzlhlry/ansible_junipernetworks.junos.junos_user_payload.zip/ansible_collections/junipernetworks/junos/plugins/modules/junos_user.py", line 311, in map_obj_to_ele
UnboundLocalError: local variable 'ssh_rsa' referenced before assignment
fatal: [switch-rsc-2-2]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "/home/lee/.ansible/tmp/ansible-local-7443558se_mcu4/ansible-tmp-1632873904.8801036-744508-196503813184442/AnsiballZ_junos_user.py", line 102, in <module>
        _ansiballz_main()
      File "/home/lee/.ansible/tmp/ansible-local-7443558se_mcu4/ansible-tmp-1632873904.8801036-744508-196503813184442/AnsiballZ_junos_user.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/lee/.ansible/tmp/ansible-local-7443558se_mcu4/ansible-tmp-1632873904.8801036-744508-196503813184442/AnsiballZ_junos_user.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.junipernetworks.junos.plugins.modules.junos_user', init_globals=None, run_name='__main__', alter_sys=True)
      File "/home/lee/.pyenv/versions/3.7.7/lib/python3.7/runpy.py", line 205, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/home/lee/.pyenv/versions/3.7.7/lib/python3.7/runpy.py", line 96, in _run_module_code
        mod_name, mod_spec, pkg_name, script_name)
      File "/home/lee/.pyenv/versions/3.7.7/lib/python3.7/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_junipernetworks.junos.junos_user_payload_mzzlhlry/ansible_junipernetworks.junos.junos_user_payload.zip/ansible_collections/junipernetworks/junos/plugins/modules/junos_user.py", line 461, in <module>
      File "/tmp/ansible_junipernetworks.junos.junos_user_payload_mzzlhlry/ansible_junipernetworks.junos.junos_user_payload.zip/ansible_collections/junipernetworks/junos/plugins/modules/junos_user.py", line 433, in main
      File "/tmp/ansible_junipernetworks.junos.junos_user_payload_mzzlhlry/ansible_junipernetworks.junos.junos_user_payload.zip/ansible_collections/junipernetworks/junos/plugins/modules/junos_user.py", line 311, in map_obj_to_ele
    UnboundLocalError: local variable 'ssh_rsa' referenced before assignment
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

**Comment by rohitthakur2590** [comment]
@lazzarello  
   Hi looks like this went off the radar. 
   FYI:  as mentioned in the [documentation](https://docs.ansible.com/ansible/latest/collections/junipernetworks/junos/junos_user_module.html#parameter-aggregate/sshkey) The `sshkey`  The ssh key argument defines the public SSH key to be configured for the user account on the remote system. This is of type string and expects a key value not the path to the key, so we have to provide the key or use a lookup plugin to get the file content by providing the path. So this is the intended behavior.
