### ISSUE TITLE
junipernetworks.junos.junos_config collection on AWX and got errors with "`PluginLoader`".

### ISSUE THREAD

**Issue by eliaspy** [ansible-collections/junipernetworks.junos#530]
##### SUMMARY
Using junipernetworks.junos.junos_config collection on AWX and got errors with "`PluginLoader`"
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
 junipernetworks.junos.junos module throwing errors when try to set config via `src` attribute that before was working just fine
##### ANSIBLE VERSION
```
junipernetworks.junos.junos_config
core 2.15.12
```

##### COLLECTION VERSION

```

```

##### CONFIGURATION

```
ansible-playbook [core 2.15.6]
  config file = /runner/project/ansible.cfg
  configured module search path = ['/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.9.18 (main, Sep  7 2023, 00:00:00) [GCC 11.4.1 20230605 (Red Hat 11.4.1-2)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
Using /runner/project/ansible.cfg as config file

```
##### OS / ENVIRONMENT
we are using <  AWX 22.6.0  > and we are hitting Junos devices with OS version >20 

##### STEPS TO REPRODUCE
- We set up config with a render temp file with jinja2

```
 - name: Set NAT configuration
    junipernetworks.junos.junos:
      src: "{{ temp_file_path }}"
      src_format: set
      update: merge
    register: result
    diff: true
    timeout: 120
```

##### ACTUAL RESULTS
This is the output error:
```
{'failed': True, 'msg': "Unexpected failure during module execution: 'PluginLoader' object has no attribute 'find_plugin_with_name'", 'exception': 'Traceback (most recent call last):\n File "/runner/requirements_collections/ansible_collections/ansible/netcommon/plugins/action/network.py", line 260, in _find_load_module\n module = importlib.import_module(context.plugin_resolved_name)\n File "/usr/lib64/python3.9/importlib/__init__.py", line 118, in import_module\n if name.startswith(\'.\'):\nAttributeError: \'NoneType\' object has no attribute \'startswith\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n File "/usr/local/lib/python3.9/site-packages/ansible/executor/task_executor.py", line 165, in run\n res = self._execute()\n File "/usr/local/lib/python3.9/site-packages/ansible/executor/task_executor.py", line 656, in _execute\n result = self._handler.run(task_vars=vars_copy)\n File "/runner/requirements_collections/ansible_collections/junipernetworks/junos/plugins/action/junos.py", line 162, in run\n result = super(ActionModule, self).run(task_vars=task_vars)\n File "/runner/requirements_collections/ansible_collections/ansible/netcommon/plugins/action/network.py", line 44, in run\n filename, module = self._find_load_module()\n File "/runner/requirements_collections/ansible_collections/ansible/netcommon/plugins/action/network.py", line 263, in _find_load_module\n fullname, filename = mloadr.find_plugin_with_name(\nAttributeError: \'PluginLoader\' object has no attribute \'find_plugin_with_name\'\n', 'stdout': '', '_ansible_no_log': False}
```

**Comment by eliaspy** [comment]
error found I had to use de full module name and not the canonical name: `junipernetworks.junos.junos` -> `junipernetworks.junos.junos_config`

Cheers.
